net:
    num_class: 20
    anchor_size: [[ 30 , 50],[ 47, 133],[ 89,  80],
                  [ 88, 218],[165, 141],[148, 291],
                  [313, 193],[237, 330],[369,355]]
    width: 1
    num_cls_head: 2
    num_reg_head: 2
