net:
    num_class: 20
    anchor_base_size: 416
    anchor_size: [[3, 36], [51, 85], [126, 75],
                  [82, 159], [178, 142], [135, 240],
                  [326, 148], [231, 282], [361, 276]]
    width: 1
    num_cls_head: 2
    num_reg_head: 2
    num_anchors: 3

    weights: [1.0, 1.0, 5.0]
